services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app:${APP_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      APP_HOST: 0.0.0.0
      APP_DB_FILE: /db_data/db.sqlite3
    volumes:
      - app-db-data:/db_data/

  migrator:
    image: app:${APP_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      APP_DB_FILE: /db_data/db.sqlite3
    volumes:
      - app-db-data:/db_data/



volumes:
  app-db-data:
    name: app-db-data
