"""rename embeddings -> embedding

Revision ID: 6cbb8fcede2d
Revises: d5b0608e2ac6
Create Date: 2024-11-09 07:06:38.010772

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6cbb8fcede2d"
down_revision = "d5b0608e2ac6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("embedding", sa.Text(), nullable=True))
    op.drop_column("users", "embeddings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("embeddings", sa.TEXT(), nullable=True))
    op.drop_column("users", "embedding")
    # ### end Alembic commands ###
